DROP TABLE IF EXISTS 'orders';
DROP TABLE IF EXISTS 'products';
DROP TABLE IF EXISTS 'shops';
DROP TABLE IF EXISTS 'lineItems';

CREATE TABLE IF NOT EXISTS 'shops'(
    'id' INTEGER PRIMARY KEY NOT NULL,
    'name' VARCHAR(255) NOT NULL,
    'createdAt' DATETIME NOT NULL,
    'updatedAt' DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS 'products'(
    'id' INTEGER PRIMARY KEY NOT NULL,
    'name' VARCHAR(255),
    'shopId' INTEGER NOT NULL REFERENCES 'shops' ('id'),
    'price' FLOAT NOT NULL,
    'createdAt' DATETIME NOT NULL,
    'updatedAt' DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS 'orders'(
    'id' INTEGER PRIMARY KEY NOT NULL,
    'shopId' INTEGER NOT NULL REFERENCES 'shops' ('id') ON DELETE CASCADE ON UPDATE CASCADE,
    'total' FLOAT NOT NULL,
    'createdAt' DATETIME NOT NULL,
    'updatedAt' DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS 'lineItems'(
    'id' INTEGER PRIMARY KEY NOT NULL,
    'productId' INTEGER NOT NULL REFERENCES 'products' ('id') ON DELETE CASCADE ON UPDATE CASCADE,
    'orderId' INTEGER NOT NULL REFERENCES 'orders' ('id') ON DELETE CASCADE ON UPDATE CASCADE,
    'quantity' INTEGER NOT NULL,
    'createdAt' DATETIME NOT NULL,
    'updatedAt' DATETIME NOT NULL
);